-- LISTAR REGISTROS POR COMPAÑIA --
CREATE PROCEDURE SP_L_EMPRESA_01
@COM_ID INT
AS
BEGIN

	SELECT * FROM TM_EMPRESA
	WHERE 
	COM_ID = @COM_ID
	AND ACTIVE = 1
END


-- OBETENER REGISTROS POR ID --
ALTER PROCEDURE SP_L_EMPRESA_02
 @EMP_ID INT
AS
BEGIN

	SELECT * FROM TM_EMPRESA
	WHERE EMP_ID = @EMP_ID
END

-- CAMBIAR ESTADO DE LA EMPRESA (DELETE)--
ALTER PROCEDURE SP_D_EMPRESA_01
@EMP_ID INT
AS
BEGIN

	UPDATE TM_EMPRESA
	SET
		ACTIVE = 0
	WHERE 
		EMP_ID = @EMP_ID
	
END
-- INSERTAR REGISTROS --
CREATE PROCEDURE SP_I_EMPRESA_01
@COM_ID INT,
@EMP_NAME VARCHAR(150),
@EMP_RUT VARCHAR(150)
AS
BEGIN

	INSERT INTO TM_EMPRESA
		(COM_ID,EMP_NAME,EMP_RUT, CREATED_AT, ACTIVE)
	VALUES
		(@COM_ID, @EMP_NAME, @EMP_RUT, GETDATE(), 1)
	
END

-- ACTUALIZAR REGISTROS --
CREATE PROCEDURE SP_U_EMPRESA_01
@EMP_ID INT,
@COM_ID INT,
@EMP_NAME VARCHAR(150),
@EMP_RUT VARCHAR(150)
AS
BEGIN

	UPDATE TM_EMPRESA
	SET
		COM_ID = @COM_ID,
		EMP_NAME = @EMP_NAME,
		EMP_RUT = @EMP_RUT
	WHERE 
		EMP_ID = @EMP_ID
	
END