-- LISTAR REGISTROS --
CREATE PROCEDURE SP_L_TIPODOC_01
AS
BEGIN 
	SELECT * FROM TM_TIPO_DOCUMENTO
	WHERE 
	ACTIVE = 1

END
-- DELETE REGISTROS --
CREATE PROCEDURE SP_D_TIPODOC_01
@TIPO_DOC_ID INT
AS
BEGIN

	UPDATE TM_TIPO_DOCUMENTO
	SET
		ACTIVE = 0
	WHERE 
		TIPO_DOC_ID = @TIPO_DOC_ID
	
END
-- INSERTAR REGISTROS --
CREATE PROCEDURE SP_I_TIPODOC_01
@DESCRIPTION VARCHAR(150)
AS
BEGIN

	INSERT INTO TM_TIPO_DOCUMENTO
		( DESCRIPTION, CREATED_AT, ACTIVE)
	VALUES
		(@DESCRIPTION, GETDATE(), 1)
	
END

-- ACTUALIZAR REGISTROS --
CREATE PROCEDURE SP_U_TIPODOC_01
@TIPO_DOC_ID INT,
@DESCRIPTION VARCHAR(150)
AS
BEGIN

	UPDATE TM_TIPO_DOCUMENTO
	SET
		DESCRIPTION = @DESCRIPTION
	WHERE 
		TIPO_DOC_ID = @TIPO_DOC_ID
	
END
