-- LISTAR REGISTROS POR SUCURSAL --
CREATE PROCEDURE SP_L_UNIDAD_DE_MEDIDA_01
@SUC_ID INT
AS
BEGIN

	SELECT * FROM TM_UNIDAD_DE_MEDIDA
	WHERE SUC_ID = @SUC_ID
END


-- OBETENER REGISTROS POR ID --
CREATE PROCEDURE SP_L_UNIDAD_DE_MEDIDA_02
 @UNI_ID INT
AS
BEGIN

	SELECT * FROM TM_UNIDAD_DE_MEDIDA
	WHERE UNI_ID = @UNI_ID
END

-- CAMBIAR ESTADO DE LA  UNIDAD DE MEDIDA (DELETE)--
CREATE PROCEDURE SP_D_UNIDAD_DE_MEDIDA_01
@UNI_ID INT
AS
BEGIN

	UPDATE TM_UNIDAD_DE_MEDIDA
	SET
		ACTIVE = 0
	WHERE 
		UNI_ID = @UNI_ID
	
END
-- INSERTAR REGISTROS --
CREATE PROCEDURE SP_I_UNIDAD_DE_MEDIDA_01
@SUC_ID INT,
@UNID_NAME VARCHAR(150)
AS
BEGIN

	INSERT INTO TM_UNIDAD_DE_MEDIDA
		(SUC_ID, UNID_NAME, CREATED_AT, ACTIVE)
	VALUES
		(@SUC_ID, @UNID_NAME, GETDATE(), 1)
	
END

-- ACTUALIZAR REGISTROS --
CREATE PROCEDURE SP_U_UNIDAD_DE_MEDIDA_01
@UNI_ID INT,
@SUC_ID INT,
@UNID_NAME VARCHAR(150)
AS
BEGIN

	UPDATE TM_UNIDAD_DE_MEDIDA
	SET
		SUC_ID = @SUC_ID,
		UNID_NAME = @UNID_NAME
	WHERE 
		UNI_ID = @UNI_ID
	
END