
-- LISTAR REGISTROS POR SUCURSAL --
CREATE PROCEDURE SP_L_CATEGORIA_01
@SUC_ID INT
AS
BEGIN

	SELECT * FROM TM_CATEGORIA
	WHERE SUC_ID = @SUC_ID
END


-- OBETENER REGISTROS POR ID --
CREATE PROCEDURE SP_L_CATEGORIA_02
 @CAT_ID INT
AS
BEGIN

	SELECT * FROM TM_CATEGORIA
	WHERE SUC_ID = @CAT_ID
END

-- CAMBIAR ESTADO DE LA CATEGORIA (DELETE)--
CREATE PROCEDURE SP_D_CATEGORIA_01
@CAT_ID INT
AS
BEGIN

	UPDATE TM_CATEGORIA
	SET
		ACTIVE = 0
	WHERE 
		CAT_ID = @CAT_ID
	
END
-- INSERTAR REGISTROS --
CREATE PROCEDURE SP_I_CATEGORIA_01
@SUC_ID INT,
@CAT_NAME VARCHAR(150)
AS
BEGIN

	INSERT INTO TM_CATEGORIA
		(SUC_ID, CAT_NAME, CREATED_AT, ACTIVE)
	VALUES
		(@SUC_ID, @CAT_NAME, GETDATE(), 1)
	
END

-- ACTUALIZAR REGISTROS --
CREATE PROCEDURE SP_U_CATEGORIA_01
@CAT_ID INT,
@SUC_ID INT,
@CAT_NAME VARCHAR(150)
AS
BEGIN

	UPDATE TM_CATEGORIA
	SET
		SUC_ID = @SUC_ID,
		CAT_NAME = @CAT_NAME
	WHERE 
		CAT_ID = @CAT_ID
	
END